title: Knowledge Quiz Test
hero_image: images/banner.png
description: Quizzy Content
version: 0.1
listed: false
copyedit: false
last_tested: 2018-10-12
steps: 
  - title: Introduction
  - title: Test Your Knowledge
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 2
      passing_score: 2
  - title: Reflection
    quiz: true
  - title: What next?
